fix: update the config mypy
osl-incubator/makim pull request #117
Opened 2024-09-29 21:50 UTC by abhijeetSaroha

Solves #116

2024-09-30 04:55 UTC, abhijeetSaroha commented
There is linter error in this line, related to subscriptable.

`AppConfigType: TypeAlias = Dict[str, Union[str, List[str]]]`

(suggestion from Claude)
The linter error occurs because built-in types like dict and list are not subscriptable in Python versions prior to 3.9 when used in type annotations. To ensure compatibility with Python 3.8 and earlier, we should use Dict and List from the typing module instead of the built-in types. If you're using Python 3.9 or later, this issue won't occur, as built-in types become subscriptable in those versions.

2024-10-03 17:20 UTC, xmnlab commented
https://github.com/osl-incubator/makim/actions/runs/11099645303/job/30834203281?pr=117#step:6:17

@abhijeetSaroha for `cast`, you will still need to use `List`,  `Tuple`, `Dict` from typing .. for the other usages, please keep using `list`, `dict`, and `tuple`

2024-10-03 17:35 UTC, abhijeetSaroha commented
Ok...I will do that and will update you.

2024-10-04 15:32 UTC, xmnlab commented
@abhijeetSaroha could you rebase this branch on top of upstream main please?

2024-10-04 16:24 UTC, abhijeetSaroha commented
I've successfully rebased the branch on top of the upstream main as requested.

Regarding the other PR, thank you for merging it! The tests for the post-run are already in place.

https://github.com/osl-incubator/makim/blob/main/tests/smoke/.makim-hooks.yaml#L23C1-L36C32

Is it OK ?

2024-10-06 16:05 UTC, xmnlab commented
> I've successfully rebased the branch on top of the upstream main.
> 
> Regarding the other PR, thank you for merging it! The tests for the post-run are already in place.
> 
> https://github.com/osl-incubator/makim/blob/main/tests/smoke/.makim-hooks.yaml#L23C1-L36C32
> 
> Is it OK ?

for some reason I missed that. that is ok. appreciate that!

2024-10-06 16:09 UTC, xmnlab commented on src/makim/console.py
> +) -> Tuple[int, int]:
this could be `tuple` if you import `from __future__ import annotations`
but I will not block this PR to be merged because of this

2024-10-06 16:22 UTC, xmnlab requested changes

2024-10-06 16:22 UTC, xmnlab commented on src/makim/core.py
> +    def _load_scoped_vars(self, scope: str) -> Any:
I would say that this should be a dict[str, Any]

```suggestion
    def _load_scoped_vars(self, scope: str) -> dict[str, Any]:
```

and in order to fix the issue with the `return`

I think it should be something like this: `return cast(Dict[str, Any], fix_dict_keys_recursively(variables))`

it is still not perfect .. but I will think some ways to improve `fix_dict_keys_recursively` .. but for now please do this change.

2024-10-06 16:22 UTC, xmnlab commented on src/makim/core.py
>          return fix_dict_keys_recursively(variables)
```suggestion
        return cast(Dict[str, Any], fix_dict_keys_recursively(variables))
```

2024-10-06 16:22 UTC, xmnlab commented on src/makim/console.py
> +) -> Tuple[int, int]:
actually there are two more changes for this PR before it is ready to go .. so please could you already fix this one as well?

2024-10-07 16:29 UTC, xmnlab approved these changes
LGTM! thanks for working on that, @abhijeetSaroha

2024-10-07 16:31 UTC, merged