checks the PR title according to semantic rel(#31)
osl-incubator/makim pull request #33
Opened 2023-04-02 16:13 UTC by git-devansh

## Pull Request description

2023-04-02 17:48 UTC, xmnlab requested changes

2023-04-02 17:48 UTC, xmnlab commented on .github/workflows/main.yaml
> +
You don't need these changes here. Just keep the implementation in the job above, please. Thanks!

2023-04-02 18:15 UTC, git-devansh commented
Thanks for your comment. This is correct?

2023-04-02 19:43 UTC, xmnlab commented
That looks better. It is missing 2 things:

- ensure you have pre-commit installed and  install the pre-commit hooks locally: `pre-commit install`
- change your PR title to fit the standard used by semantic release. You can check the standard defined here: https://github.com/arxlang/arx/blob/main/CONTRIBUTING.md#commit-message-format ..  probably something starting with `chore(ci)` would be enough

2023-04-22 00:13 UTC, xmnlab approved these changes
thanks for working on that @git-devansh !

sorry for the delay here. also feel free to ping me here on github or on discord to request more reviews!

2023-04-22 00:13 UTC, merged