WIP: flat to src layout
osl-incubator/makim pull request #63
Opened 2023-11-23 14:27 UTC by abhijeetSaroha

2023-11-23 18:03 UTC, xmnlab requested changes
LGTM! thanks for working on that

2023-11-23 18:03 UTC, xmnlab commented on pyproject.toml
> +include = ["src/makim/*"]
```suggestion
packages = [
  {include = "makim", from="src"},
]
include = ["src/makim/py.typed"]
```

2023-11-23 18:04 UTC, xmnlab commented on pyproject.toml
> +include = ["src/makim/*"]
create a `src/makim/py.typed` file, as an empty file

2023-11-24 09:45 UTC, abhijeetSaroha commented
I have created the `src.makim/py.typed` file, an empty file. I think it works fine, can you please verify it?

2023-11-24 10:32 UTC, xmnlab approved these changes
@abhijeetSaroha , LGTM! thanks for working on that!

2023-11-24 10:33 UTC, merged